### ISSUE TITLE
libsqsh uses size_t for file sizes/offsets

### ISSUE THREAD

**Issue by Dr-Emann** [Gottox/sqsh-tools#280]
**Describe the bug**

On a 32 bit system, the max value of a `size_t` is 4 GiB. A squashfs archive is allowed to be much larger than that (or should be allowed to start at an offset larger than that.

For example, the [`SqshMemoryMapperImpl::init`](https://gottox.de/sqsh-tools/doxygen/structSqshMemoryMapperImpl.html#a75e0296ef505f676e1e98680107863bf) function is expected to write the source size to a `size_t *size` pointer, and the map function recieves an offset in a `sqsh_index_t offset` (where `sqsh_index_t` is [a typedef for `size_t`](https://gottox.de/sqsh-tools/doxygen/sqsh__common_8h.html#a1d493fd70fce488d899c7681d5ff6264)) parameter.

**Comment by Gottox** [comment]
There are lot's of conversation issues on 32bit at the moment. I'll take a look at it. Thanks for reporting!
